[package]
authors = ["Adrian Perez de Castro <aperez@igalia.com>"]
description = "FFI bindings for libicecc"
name = "libicecc-sys"
version = "0.1.0"
build = "build.rs"

[build-dependencies]
gcc = "0.3"
pkg-config = "0.3"

[dependencies]
libc = "0.2"
